name: Django CI

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      image_name:
        required: true
        type: string
      harbor_project:
        required: false
        type: string
        default: "minhdqdev"
      harbor_registry:
        required: false
        type: string
        default: "harbor.minhdq.dev"
      dockerfile:
        required: false
        type: string
        default: "./deploy/dockerfile"
      runs_on:
        required: false
        type: string
        default: '["self-hosted", "minhdqdev-org", "manual"]'
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ${{ fromJson(inputs.runs_on) }}
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: version
        run: |
          if [ -f "pyproject.toml" ]; then
            VERSION=$(grep -E '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          else
            echo "pyproject.toml not found, using run number"
            VERSION="0.0.${{ github.run_number }}"
          fi
          
          if [ -z "$VERSION" ]; then
            echo "Could not extract version, using run number"
            VERSION="0.0.${{ github.run_number }}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.harbor_registry }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ inputs.harbor_registry }}/${{ inputs.harbor_project }}/${{ inputs.image_name }}:${{ steps.version.outputs.VERSION }}
            ${{ inputs.harbor_registry }}/${{ inputs.harbor_project }}/${{ inputs.image_name }}:latest
            ${{ inputs.harbor_registry }}/${{ inputs.harbor_project }}/${{ inputs.image_name }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ inputs.harbor_registry }}/${{ inputs.harbor_project }}/${{ inputs.image_name }}:buildcache
          cache-to: type=registry,ref=${{ inputs.harbor_registry }}/${{ inputs.harbor_project }}/${{ inputs.image_name }}:buildcache,mode=max
